name: Deploy build on lactame.com

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15.x'
      - name: Install GWT 2.9
        run: ./scripts/get-gwt.sh
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to lactame.com
        uses: zakodium/lactame-action@v1
        with:
          token: ${{ secrets.LACTAME_TOKEN }}
          name: openchemlib
          folder: dist
