name: Node.js CI

on:
  push:
    branches: master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'
      - name: Install GWT 2.9
        run: |
          wget https://storage.googleapis.com/gwt-releases/gwt-2.9.0.zip -O gwt.zip
          unzip -q gwt.zip
          mv gwt-2* gwt
          echo '{"gwt": "./gwt"}' > config.json
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build OCL
        run: npm run build
      - name: Run tests
        run: npm run test
